name: Deploying tags

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - run: |
          echo "deploying tag ${GITHUB_REF_NAME}"
